# Docker Compose file for TurtleBot3 Behavior Examples
#
# Usage:
#
# To build the images:
#   docker compose build
#
# To start up a specific service by name:
#   docker compose up <service_name>
#
# To open an interactive shell to a running container:
#   docker exec -it <container_name> bash

version: "3.9"
services:
  # Base image containing dependencies.
  base:
    image: driver_stm:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: iron
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev/stm32act:/dev/stm32act
      - /dev/input:/dev/input

  # Overlay image containing the example source code.
  overlay:
    extends: base
    image: driver_stm:overlay
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay

  # Developer container
  dev:
    extends: overlay
    image: driver_stm:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      # Mount the source code
      - ./holonomic_twist_keyboard:/overlay_ws/src/holonomic_twist_keyboard:rw
      - ./stm32_to_tos_rasp:/overlay_ws/src/stm32_to_tos_rasp:rw
      - ./wheel_speeds_converter:/overlay_ws/src/wheel_speeds_converter:rw
      # Mount colcon build artifacts for faster rebuilds
      - ./.colcon/build/:/overlay_ws/build/:rw
      - ./.colcon/install/:/overlay_ws/install/:rw
      - ./.colcon/log/:/overlay_ws/log/:rw
      - /dev/input:/dev/input
    command: sleep infinity

  # # Runs basic TurtleBot3 simulation
  # sim:
  #   extends: overlay
  #   command: ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py

  # # Demo world
  # demo-world:
  #   extends: overlay
  #   command: ros2 launch tb3_worlds tb3_demo_world.launch.py

  # # Behavior demo using Python and py_trees
  # demo-behavior-py:
  #   extends: overlay
  #   command: >
  #     ros2 launch tb3_autonomy tb3_demo_behavior_py.launch.py
  #     tree_type:=${BT_TYPE:?}
  #     enable_vision:=${ENABLE_VISION:?}
  #     target_color:=${TARGET_COLOR:?}

  # # Behavior demo using C++ and BehaviorTree.CPP
  # demo-behavior-cpp:
  #   extends: overlay
  #   command: >
  #     ros2 launch tb3_autonomy tb3_demo_behavior_cpp.launch.py
  #     tree_type:=${BT_TYPE:?}
  #     enable_vision:=${ENABLE_VISION:?}
  #     target_color:=${TARGET_COLOR:?}